config/routes.rb
Rails.application.routes.draw do
  
  get '/auth/facebook/callback' => 'sessions#facebook'
  get 'auth/failure', to: redirect('/')
  
  root 'sessions#welcome'

  get '/home' => 'sessions#home'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#login'

  get '/logout' => 'sessions#logout'
   
  resources :users
    
  resources :locations do
    resources :tasks
  end

  resources :locations do
    delete :destroy
  end
  
  resources :tasks
    get '/404', :to => 'errors#not_found'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :tasks, dependent: :destroy
    has_many :users, through: :tasks

    validates_presence_of :name

end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    belongs_to :location, optional: true

    validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    has_many :tasks, dependent: :destroy
    has_many :locations, through: :tasks

    validates_presence_of :name
    validates :email, uniqueness: { message: "Email already in use, please try a different email or Login."}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?, :require_login
  
    def current_user
      current_user ||= User.find_by(id: session[:user_id])
    end
  
    def logged_in?
      !!current_user
    end

    def require_login
      redirect_to '/' unless session.include? :user_id
    end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  
  def not_found
    render :status => 404
  end
  
end
  

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    before_action :require_login
    before_action :set_location, only: [:show, :edit, :update, :destroy] 

    def index
        @locations = Location.all
    end

    def new
        @location = Location.new
    end

    def create
        @location = Location.new(location_params)
        if @location.save
            redirect_to location_path(@location)
        else
            redirect_to new_location_path(@location), error: "Error: #{@location.errors.full_messages.join(", ")}"
        end
    end

    def show
        @location = Location.find_by_id(params[:id])
        @users = @location.users
    end

    def edit
        @location = Location.find_by_id(params[:id])
        render :edit
    end

    def update
        @location = Location.find_by(id: params[:id])
        if @location.update(location_params)
            redirect_to location_path(@location)
        else
            redirect_to edit_location_path(@location), error: "Error: #{@location.errors.full_messages.join(", ")}"
        end
    end

    def destroy
        Location.find(params[:id]).destroy
        flash[:notice] = "Location deleted."
        redirect_to '/locations/'
    end

    
    private

    def location_params
        params.require(:location).permit(:name, :notes, :task_ids => [])
    end

    def set_location
        @location = Location.find_by(id: params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_login, only: [:logout]
    before_action :set_user, only: [:home]

    def welcome
    end

    def home
    end

    def new
        @user = User.new
        render 'login'
    end

    def facebook
        @user = User.find_or_create_by(uid: auth['uid']) do |c|
            c.name = auth['info']['name']
            c.email = auth['info']['email']
            c.password = SecureRandom.urlsafe_base64
            c.job ||= "Contributor"
        end
        if @user.save
            session[:user_id] = @user.id
            redirect_to home_path
        else
            redirect_to root_path
        end
    end

    def login
        @user = User.find_by(name: params[:user][:name])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to home_path
        else
            redirect_to login_path
        end
    end
    
    def logout
        if session[:user_id]
            session.clear
            redirect_to root_path
        else
            redirect_to home_path
        end
    end

    private

    def auth
        request.env['omniauth.auth']
    end

    def set_user
        @user = User.find_by(:id => session[:user_id])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :require_login
    before_action :set_location, only: [:edit, :update]
    before_action :set_task, only: [:show, :edit, :update]

    def index
        @tasks = Task.all
        if params[:location_id]
            @task = Task.new(location_id: params[:location_id])
        else
            @task = Task.new
        end
    end

    def new
        @task = Task.new(location_id: params[:location_id])
    end

    def create
        @task = Task.new(task_params)
        if @task.save!
            redirect_to task_path(@task)
        else
            redirect_to new_task_path(@task), error: "Error: #{@task.errors.full_messages.join(", ")}"
        end
    end

    def show
        @task = Task.find_by(id: params[:id])
    end

    def edit
        @task = Task.find_by(id: params[:id])
        render :edit
    end

    def update
        @task = Task.find_by(id: params[:id])

        @task.update(task_params)
        if @task.save
            redirect_to task_path(@task)
        else
            redirect_to edit_task_path(@task), error: "Error: #{@task.errors.full_messages.join(", ")}"
        end
    end

    def destroy
        Task.find(params[:id]).destroy
        flash[:notice] = "Task deleted."
        redirect_to '/tasks/'
    end

    
    private

    def task_params
        params.require(:task).permit(:name, :description, :user_id, :location_id, :user_name)
    end

    def set_task
        @task = Task.find_by(:location_id => params[:location_id], :id => params[:id])
    end

    def set_location
        @location = Location.find_by(id: params[:location_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, except: [:new, :create]

    def index
        @users = User.all
    end
    
    def new
        @user = User.new
    end  

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user), notice: "User sign up was successful."
        else
            redirect_to new_user_path, error: "Error: #{@user.errors.full_messages.join(", ")}"
        end
    end

    def show
        @user = User.find_by(id: params[:id])
    end

    def edit
        @user = User.find_by(id: current_user.id)
        render :edit
    end

    def update
        @user = User.find_by(id: params[:id])

        @user.update(user_params)
        if @user.save
            redirect_to user_path(@user)
        else
            redirect_to edit_user_path(@user), error: "Error: #{@user.errors.full_messages.join(", ")}"
        end
    end

    def destroy
        if User.find_by(:id => params[:id]) == current_user
            User.find_by(:id => params[:id]).destroy
            session.clear   # if admin deletes themself, they get logged out
            redirect_to '/'
        elsif User.find_by(:id => params[:id]).destroy
            User.find_by(:id => params[:id]).destroy
            flash[:notice] = "Crew record deleted."
            redirect_to users_path
        else
            redirect_to users_path, error: "This action requires clearance"
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :job, :email, :uid, :password, :password_confirmation, :location_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task Manager</title>
    <%= csrf_meta_tags %>

  <body>
    
    <div class="wrapper">
      <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
      <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
      <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
    
      <%= yield %>

      <footer class="branding">
      <% if request.path != "/home" && request.path != "/" && request.path != "/login" && logged_in?%>
        <a href="/home"><button>Home</button></a>
      <% end %>
      <% if logged_in? %>
        <a href="/logout" onclick="return confirm('Log Out?');"><button>Log Out</button></a>
      <% end %>
      </footer>
    </div>
    
  </body>
</html>

app/views/locations/edit.html.erb
<h1>Edit Location</h1>

<%= form_for @location do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :notes %>
    <%= f.text_area :notes %><br><br>
    <br></br>
    <%= f.submit %>
<% end %>

<% if @location.errors.any? %>
  <div class="error_explanation">
    <% @location.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
  </div>
<% end %>

app/views/locations/index.html.erb
<h2>Current Locations</h2>
<div class="content">
    <ul id="locations_list">
    <% @locations.each do |s| %>
        <li><%= link_to "#{s.name}", location_path(s) %></li>
    <% end %>
    </ul>
</div>

<div class="sidebar">
    <h3>Menu</h3>
    <ul>
        <li><%= link_to "Add a new location", new_location_path %></li>
    </ul>
</div>

app/views/locations/new.html.erb
<h1>New Location Form</h1>

<%= form_for @location do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :notes %>
    <%= f.text_area :notes %><br></br>
    
    <p>Create Task?</p>
    <%= f.fields_for :tasks, @location.tasks.build do |a| %>
        
        <p>Select a user:
        <%= select_tag 'location[tasks_attributes][0][user_id]', content_tag(:option,'select one...',:value=>"")+options_from_collection_for_select(User.all, :id, :name) %></p>

        <%= a.hidden_field :location_id, value: @location.id %>

        <%= a.label :name, "Task Name" %>
        <%= a.text_field :name %><br>
        <%= a.label :description %>
        <%= a.text_field :description %>
    <% end %>
    <br>
    <%= f.submit %>
<% end %>

<% if @location.errors.any? %>
  <div class="error_explanation">
    <% @location.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
  </div>
<% end %>

app/views/locations/show.html.erb
<h1>Location Information</h1>

<h2><%= @location.name %></h2>
<ul>
    <li>Notes: <%= @location.notes if @location.notes %></li>
</ul><br>

<h3>Current Users</h3>
<ul>
<% @users.each do |c| %>
    <% a = Task.find_by(:location_id => @location.id, :user_id => c.id) %>
    <li><%= link_to "#{c.name}", location_task_path(@location, a) %></li>
<% end %>
</ul>
<br>
<p><%= link_to "Add task", new_location_task_path(@location) %></p>
<br></br>


<p><%= link_to "Edit this location's info", edit_location_path(@location) %><%= form_tag location_path(@location.id), method: "delete" do %>
    <%= submit_tag "Delete location" %>
  <% end %>

app/views/tasks/_form.html.erb
<%= form_for([@location, @task]) do |f| %>
    
    <strong><%= f.label :name %></strong>
    <%= f.text_field :name %><br>
    
    <strong><%= f.label :description %></strong>
    <%= f.text_field :description %><br></br>
    
    <strong><%= f.label :location_id %></strong><br>
    <!-- <%= f.collection_check_boxes :location_id, Location.all, :id, :name %><br></br> -->
    <%= f.select(:location_id) do %>
        <%= options_from_collection_for_select(Location.all, :id, :name, :selected => @task.location_id) %>
    <% end %>

    <br></br>
    <strong><%= f.label :user_id %></strong><br>
    <!--<%= f.collection_check_boxes :user_id, User.all, :id, :name %><br> -->
    <%= f.select(:user_id) do %>
        <%= options_from_collection_for_select(User.all, :id, :name, :selected => @task.user_id) %>
    <% end %>

    <br></br>
    <!-- <%= f.submit %> -->
    <button type="submit" name="commit" value="Create Task">Create Task</button>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit this Task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>All Tasks for all Locations:</h1>
<ul id="taskList">
<% @tasks.each do |s| %>
    <li><%= link_to "#{s.name}", task_path(s) %></li>
<% end %>
</ul>
<br>

<div class="sidebar">
    <h3>Menu</h3>
    <ul>
        <li><%= link_to "Add a new Task", new_task_path %></li>
    </ul>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h2>Task Information</h2>

Name: <%= @task.name %><br>
Description: <%= @task.description %><br>
Location: <%= @task.location.name %><br>
Assigned to: <%= @task.user.name %><br>
<br></br>
<p><%= link_to "Edit this task", edit_task_path(@task.id) %></p>
<%= form_tag task_path(@task.id), method: "delete" do %>
    <%= submit_tag "Delete task" %>
  <% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :job %>
    <%= f.text_field :job %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <%= f.label :password %>
    <%= f.text_field :password %>
    <br>
    <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User Info</h1>

<%= render partial: 'form', locals: {user: @user} %>

app/views/users/index.html.erb
<h1>Current User List:</h1>
<ul>
<% @users.each do |c| %>
    <li><%= "#{c.name}" %> <%= link_to "Profile", user_path(c) %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Welcome!</h1>

<%= render 'form' %>

<br></br>
<p>Already a user? <%= link_to "Log In", login_path %></p>

app/views/users/show.html.erb
<h1>User Info: </h1>

<div>
    <ul>
        <li>Name: <%= @user.name %></li>
        <li>Position: <%= @user.job %></li>
        <li>Current task(s):
            <% if @user.tasks %>
                <% @user.tasks.each do |a| %>
                    <%= link_to a.name, location_task_path(a.location, a) %>
                <% end %>
            <% end %></li>
        <br>
    </ul>
<br>
<br>